TITLE       := Store
VERSION     := 2.00
TITLE_ID    := NPXS39041
CONTENT_ID  := IV0002-NPXS39041_00-STOREPS500000000

TOOLCHAIN   := $(OO_PS4_TOOLCHAIN)

UNAME_S := $(shell uname -s)

ifeq ($(UNAME_S),Linux)
CDIR := linux
endif

ifeq ($(UNAME_S),Darwin)
CDIR := macos
endif

all:
	@echo "PS5 package uses existing homebrew.elf"
